### ISSUE TITLE
[Help Required] Title Getting "Unexpected token < in JSON at position 0" error while working with JSON Data

### ISSUE THREAD

**Issue by Teshmi** [yesoreyeram/grafana-infinity-datasource#19] opened 2020-12-21 06:33 UTC
Hi Team,

            I am trying to use the Infinity datasource in Grafana as guided. Could able to retrieve the data if using inline JSON , but when using JSON URL getting "Unexpected token < in JSON at position 0" error and no response.

          Same URL is tested in REST Client - Postman, and successfully getting the response. Could you please help in understanding the root cause of the problem and resolving the issue.

Thanks & Regards,
Teshmi

**Comment by yesoreyeram** [comment] 2020-12-21 06:53
Duplicate of #6

**Closed** 2020-12-21 06:53 UTC
Labels: help wanted
