### ISSUE TITLE
Adding proxy authentication in routes

### ISSUE THREAD

**Issue by Na-ru-to4170** [yesoreyeram/grafana-infinity-datasource#29] opened 2021-02-12 12:33 UTC
**Is your feature request related to a problem? Please describe.**
I am creating a dashboard for api end point which is using authentication token to fetch the details from api. And this token is only valid for one hour.
So what tried to add it in custom header which is present in UI:
![image](https://user-images.githubusercontent.com/78961986/107768013-ce911c00-6d5b-11eb-9dcf-9411ca5ec86c.png)
but for this we have to change the token in every one hour.

**Describe the solution you'd like**
What we did is adding the entry in plugin.json which will redirect calls which is generated via user and will add token so that request are completed and give us result
![image](https://user-images.githubusercontent.com/78961986/107768355-4fe8ae80-6d5c-11eb-8822-835a05d95179.png)

This will enable us to use any endpoint which uses token for authentication.

**Comment by Na-ru-to4170** [comment] 2021-02-12 12:44
Added the PR:
https://github.com/yesoreyeram/grafana-infinity-datasource/pull/30

**Comment by yesoreyeram** [comment] 2021-02-14 18:02
Closing as duplicate of #7 .

**Closed by yesoreyeram** 2021-02-14 18:02 UTC
