### ISSUE TITLE
message:"error getting response from" Error 500

### ISSUE THREAD

**Issue by felipegimenez** [yesoreyeram/grafana-infinity-datasource#136] opened 2021-08-24 22:27 UTC
Hello, @yesoreyeram!

First, congratulations for your work with grafana-infinity-datasource. It's a very nice plugin.

I tried use the plugin, but i got this error in Grafana Dashboard:
```
error getting response from https://jsonplaceholder.typicode.com/users
Object
status:500
statusText:"Internal Server Error"
data:Object
message:"error getting response from https://jsonplaceholder.typicode.com/users
"
error:"Internal Server Error"
response:"error getting response from https://jsonplaceholder.typicode.com/users
"
config:Object
method:"POST"
url:"api/datasources/110/resources/proxy"
data:Object
retry:0
headers:Object
hideFromInspector:true
message:"error getting response from https://jsonplaceholder.typicode.com/users
```

Log of application:
`lvl=eror msg="Request Completed" logger=context = orgId=1 method=POST path=/api/datasources/266/resources/proxy status=500
`

Can you help me?

**Comment by yesoreyeram** [comment] 2021-08-24 22:31
Make sure no URL specified in the datasource config. Having conflicting URLs may cause this issue.

**Comment by felipegimenez** [comment] 2021-08-25 01:01
![Captura de Tela 2021-08-24 às 21 33 52](https://user-images.githubusercontent.com/16758763/130707499-a369ebcf-95d0-48d5-92e2-f5343e02b5cf.png)

Base URL is empty.
Version Plugin Infinity: 0.7.8
Version Grafana: 8.1.2

**Comment by yesoreyeram** [comment] 2021-08-25 13:40
Duplicate of https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/137.

**Closed by yesoreyeram** 2021-08-25 13:40 UTC
