### ISSUE TITLE
Dashboard variables in results filter

### ISSUE THREAD

**Issue by afletch** [yesoreyeram/grafana-infinity-datasource#196] opened 2021-11-10 11:49 UTC
The results filter does not appear to support the use of dashboard variables. Is this a bug or by design?

**Comment by jykae** [comment] 2021-11-17 11:14
Would be cool to filter results with dashboard time range 👍

**Comment by m-gnaedig** [comment] 2022-01-21 11:03
Dashboard variables in the result filter would be very useful also for my use case.
During my tests it was not working. Is there any plan to implement it?

**Comment by yesoreyeram** [comment] 2022-01-21 14:46
yea.. definitely a good to have feature. I will add this to my backlog and work when I have some time. If anyone else can, feel free to PR.

**Comment by m-gnaedig** [comment] 2022-01-22 09:12
Super... Thank you very much. I am sure many people will use it.

**Comment by yesoreyeram** [comment] 2022-02-02 10:39
hmm... Just noticed that this already works. https://grafana-infinity-datasource.herokuapp.com/d/data-filter-by-variable

Can someone tell how to reproduce this if not working for you? @m-gnaedig ??

**Comment by yesoreyeram** [comment] 2022-04-20 10:36
Since this is not reproducible, closing this issue.

**Closed by yesoreyeram** 2022-04-20 10:36 UTC

**Comment by ebachman24** [comment] 2022-04-21 18:44
I have been able to use Grafana variables within a given Infinity dashboard panel.  That part works.  

However, I think what this ticket might have been getting at is that the results filter doesn't work when trying to use Infinity datasource AS a Grafana variable.

Grafana Dashboard Settings --> Variable --> New --> Then use the Infinity data source and apply a results filter

![image](https://user-images.githubusercontent.com/104096952/164531477-ea4bade2-86a0-49a1-86e7-06f00167b84e.png)
