### ISSUE TITLE
[Bug] Can't set columns in Dashboard Variables

### ISSUE THREAD

**Issue by psycholock13** [yesoreyeram/grafana-infinity-datasource#87] opened 2021-06-11 10:50 UTC
Hello there.

**Describe the bug**
When I try to add a variable to the dashboard(Dashboard Settings => Variables) and set columns, it fails.
Parameters:
Data Source: Infinity.
Query Type: infinity.
Type: JSON.
Source: URL.
URL: set.
Rows / Root: builds.

At this moment I get data from my host - looks nice.
But then I click "Add columns", I try to enter data in any field (selector / string), and it turns out to enter only one character and then everything looks very buggy.
I would also like to clarify that absolutely the same parameters in Panels work perfectly and there I can add and remove columns.

**Screenshots**
The first screenshot shows that the data is being received.
On the gif, I'm trying to add a Column, but only one character is entered, and when I try to enter the second, the button at the bottom starts flickering(specifically, rows / root are not filled here, but the behavior is exactly the same with a filled field).
![fe296879432dca24cdb3c9ad305aa45b](https://user-images.githubusercontent.com/85739407/121674388-aa9bd800-caba-11eb-81cd-f5bb7c50e189.png)
![595b465da8d6adff03906141dce0372f](https://user-images.githubusercontent.com/85739407/121674398-ad96c880-caba-11eb-9174-cb230a8ab12e.gif)

**Version Details:**

- Grafana version : v8.0.0 (41f0542c1e)
- Plugin version : 0.7.0

I would be glad to receive any help, this is very important to us.
Thanks in advance.

**Comment by yesoreyeram** [comment] 2021-06-11 15:18
Thanks for reporting this issue. Possibly this is a duplicate of #32

**Comment by yesoreyeram** [comment] 2021-06-22 09:40
This is now fixed in v0.7.3. Feel free to reopen if you see anything unexpected.

**Closed by yesoreyeram** 2021-06-22 09:40 UTC
Labels: bug
