### ISSUE TITLE
[Bug] Graphql Dashboard variables no longer work after grafana upgrade

### ISSUE THREAD

**Issue by abferm** [yesoreyeram/grafana-infinity-datasource#191] opened 2021-11-03 16:20 UTC
**Describe the bug**
We had fallen behind on grafana updates and was trying to upgrade from 7.2.1 to 8.2.X, but found that my variable queries no longer worked after 7.4.0.
**Version Details:**

- Grafana version : 7.4.0+
- Plugin version : 0.7.8, 0.7.10

**Additional context**
My broken variable queries use Graphql with "Rows / Root" and columns to specify name and value. I do not have any variable queries that don't use these features.
The same query works fine in a table.

**Comment by yesoreyeram** [comment] 2021-11-03 16:34
Can you specify exact steps to reproduce the issue? Looks like a duplicate of #32 . Feel free to reopen if it is not.

**Comment by abferm** [comment] 2021-11-03 17:12
#32 Appears to be about a problem with the editor, my issue appears to be with the actual execution of the query.

The graphql request returns both before and after upgrading grafana:
```json
{"data":{"wells":{"edges":[{"node":{"name":"Principal","id":"V2VsbApsMQ=="}},{"node":{"name":"Games, Outdoors \u0026 Tools","id":"V2VsbApsMg=="}},{"node":{"name":"Beauty, Clothing \u0026 Outdoors","id":"V2VsbApsMw=="}},{"node":{"name":"Investment Account","id":"V2VsbApsNA=="}},{"node":{"name":"connecting","id":"V2VsbApsNQ=="}},{"node":{"name":"virtual","id":"V2VsbApsNg=="}},{"node":{"name":"Realigned","id":"V2VsbApsNw=="}},{"node":{"name":"Shoes \u0026 Health","id":"V2VsbApsOA=="}},{"node":{"name":"THX","id":"V2VsbApsOQ=="}},{"node":{"name":"one-to-one","id":"V2VsbApsMTA="}}]}}}
```

But after updating grafana the values are no longer populated.

Screnshots:
**Before**
![before_upgrade](https://user-images.githubusercontent.com/3749715/140133627-b66237c5-ed16-4e43-86d5-0f7b51a4c404.png)

**After**
![after_upgrade](https://user-images.githubusercontent.com/3749715/140133643-a774359d-c8aa-4ef7-a528-a6f0be658126.png)

**Comment by abferm** [comment] 2021-11-03 21:46
I managed to reproduce against a public graphql api. See the attached dashboard.

Steps to reproduce:
1. Run grafana/grafana:7.2.1 docker image, install infinity plugin via environment variable
2. Load Dashboard json
3. Observe values for variable
4. Run grafana/grafana:8.2.3 docker image, install infinity plugin via environment variable
5. Load Dashboard json
6. Observe variable value empty except for "None" option

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "description": "",
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 3,
  "iteration": 1635975321610,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "align": null,
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "filterable": false,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.2.1",
      "targets": [
        {
          "columns": [],
          "csv_options": {
            "columns": "",
            "comment": "",
            "delimiter": ",",
            "relax_column_count": false,
            "skip_empty_lines": false,
            "skip_lines_with_error": false
          },
          "data": "",
          "filters": [],
          "format": "table",
          "global_query_id": "",
          "refId": "A",
          "root_selector": "data.continent.countries",
          "source": "url",
          "type": "graphql",
          "url": "https://countries.trevorblades.com/",
          "url_options": {
            "data": "query {\n  continent(code: \"$country_code\") {\n    countries {\n      name\n      capital\n      phone\n    }\n  }\n}",
            "method": "POST"
          }
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": true,
          "text": "Antarctica",
          "value": "AN"
        },
        "datasource": "Infinity",
        "definition": "Infinity- (infinity) ",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "Country",
        "multi": false,
        "name": "country_code",
        "options": [],
        "query": {
          "infinityQuery": {
            "columns": [
              {
                "selector": "name",
                "text": "name",
                "type": "string"
              },
              {
                "selector": "code",
                "text": "code",
                "type": "string"
              }
            ],
            "csv_options": {
              "columns": "",
              "comment": "",
              "delimiter": ",",
              "relax_column_count": false,
              "skip_empty_lines": false,
              "skip_lines_with_error": false
            },
            "data": "",
            "filters": [],
            "format": "table",
            "refId": "variable",
            "root_selector": "data.continents",
            "source": "url",
            "type": "graphql",
            "url": "https://countries.trevorblades.com/",
            "url_options": {
              "data": "# Write your query or mutation here\nquery{\n  continents{\n    name\n    code\n  }\n}",
              "method": "POST"
            }
          },
          "query": "",
          "queryType": "infinity"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Countries Copy",
  "uid": "sKxlaEFnk",
  "version": 4
}
```

**Comment by abferm** [comment] 2021-11-05 15:17
@yesoreyeram 
I agree with @chriswiggins. This appears to be a duplicate of #181 and these two appear to be distinct from #32 

Since I am not a "collaborator" I am not able to reopen an issue you have closed. Can you please re-open this issue or #181 to track this issue separately.

**Closed** 2021-11-09 11:24 UTC
Labels: bug

**Comment by yesoreyeram** [comment] 2021-11-09 13:34
v0.8.0-dev.6 release should fix this. temp demo page https://grafana-infinity-datasource.herokuapp.com/d/FpHVrG57k/191-variables-not-working?orgId=1

Lets know if it is not working as expeceted

Download : https://github.com/yesoreyeram/grafana-infinity-datasource/releases/tag/v0.8.0-dev.6
